config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :registrations, only: [:new, :create]
  post '/registrations/new' => 'registrations#create'
  get '/logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'registrations#facebook'
  get '/auth/twitter/callback', to: 'registrations#twitter'
 
  resources :parents, only: [:show, :update] do
    resources :todos, only: [:index, :new, :show, :create,:destroy, :update] do
      resources :tasks, only: [:new, :create, :destroy, :update]
    end
  end

  resources :admin, only: [:index, :show, :edit, :update, :destroy]
  post '/admin/:id/edit' => 'admin#update'
  post '/parents/:id' => 'admin#update'

  post '/todos/new' => 'todos#create'
  post '/todos/:id/tasks/:id' => 'tasks#update'

  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  get '/terms' => 'welcome#terms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_secure_password
  has_many :tasks
  has_many :todos, through: :tasks
  

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :parent
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :parent
  has_many :tasks

  def self.late_todos
    self.all.where('done = ? AND duedate < ?', false, Date.today)
  end

  def tasks_attributes=(tasks_attrs)
    tasks_attrs.each do |key, task_hash|
      tasks.build(task_hash) if !task_hash.empty?
    end
  end
end

app/models/user_mailer.rb
class UserMailer < ActionMailer::Base
  default :from => "noreply@parental.bengreenberg.org"

  def reminder_email
    @todos = Todo.all
    @todos.each do |todo|
      if todo.duedate == Date.today || todo.duedate == Date.tomorrow && todo.done == false
        mail(:to => "#{todo.parent.name} <#{todo.parent.email}>", :subject => "parental: you have a todo that needs to get done")
      end
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :is_admin?
  helper_method :current_parent

  def index
    @parents = Parent.all
  end

  def show
    current_parent
  end

  def edit
    current_parent
  end

  def update
    current_parent.update(parent_params)
    current_parent.save
    redirect_to admin_path(current_parent)
  end

  def destroy
    current_parent.delete
    redirect_to admin_index_path
  end

  private

  def parent_params
    params.require(:parent).permit(:name, :email, :admin)
  end

  def is_admin?
    if current_user && current_user.admin == true
    else
      redirect_to new_session_path
    end
  end

  def current_parent
    @parent = Parent.find_by(id: params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= Parent.find_by(id: session[:parent_id])
  end
  helper_method :current_user


  def logged_in?
    redirect_to new_session_path if !session[:parent_id]
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :logged_in?

  def index
    @todo = Todo.find_by(params[:id])
  end
  
  def show
    @current_todo = find_todo(params[:id]) || current_user.todos.last
    @parent = current_user
    @todo = @parent.todos.build
    @todos = all_todos(@parent)
    @tasks = current_user.tasks.where(todo_id: params[:id])
    @task = @todo.tasks.new
  end

  private

  def find_todo(todo)
    @todo = Todo.find_by(id: params[:id])
  end

  def all_todos(parent)
    Todo.left_outer_joins(:parent).where('parent_id = ? AND done = ?', @parent.id, false)
  end
end

app/controllers/registrations_controller.rb
require 'securerandom'
class RegistrationsController < ApplicationController

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.new(parent_params)
    if @parent.save
      session[:user_id] = @parent.id
      redirect_to parent_path(@parent)
    else
      flash[:alert] = "signup failed. please try again."
      redirect_to '/registrations/new'
    end
  end

  def facebook
    @parent = Parent.find_or_create_by(uid: auth['uid'])
    if @parent.persisted? == false
      @parent.name = auth['info']['name']
      @parent.email = auth['info']['email']
      @parent.image = auth['info']['image']
      @parent.password = SecureRandom.hex
      @parent.save
      session[:parent_id] = @parent.id
      redirect_to parent_path(@parent)
    else
      session[:parent_id] = @parent.id
      redirect_to parent_path(@parent)
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end

  def parent_params
    params.require(:parent).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @parent = Parent.find_by(params[:email])
  end

  def create
    @parent = Parent.find_by(:email => params[:email])
    if @parent && @parent.authenticate(params[:password])
      session[:parent_id] = @parent.id
      redirect_to parent_path(@parent)
    else
      flash[:alert] = "login failed. please try again."
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    session.clear
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in?

  def new
    @task = @todo.tasks.build
  end

  def create
    @todo = Todo.find_by(id: params[:todo_id])
    @task = @todo.tasks.build(task_params)
    @task.todo_id = @todo.id
    @task.parent_id = @todo.parent_id
    @task.save
    redirect_to request.referrer
  end

  def update
    @parent = current_user
    @task = @parent.tasks.find_by(id: params[:task][:task_id])
    @task.update(done: params[:task][:done])
    @task.save
    redirect_to request.referrer
  end

  private

  def task_params
    params.require(:task).permit(:title, :parent_id, :todo_id, :id, :task, :done)
  end
end

app/controllers/todos_controller.rb
require 'pry'
class TodosController < ApplicationController
  before_action :logged_in?

  def index
    @parent = current_user
    @todo = @parent.todos.build
    @todos = all_todos(@parent)
  end

  def new
    @todo = Todo.new
    @task = @todo.tasks.build
  end

  def create
    @parent = current_user
    @todo = Todo.new(todo_params)
    @todo.parent_id = @parent.id
    if @todo.save
      respond_to do |f|
        f.json {render :json => @todo}
        f.html { redirect_to request.referrer }
      end
    end
  end

  def show     
    find_todo(@todo)
    @tasks = current_user.tasks.where(todo_id: params[:id])
    # @task = @todo.tasks.build
    render :json => @todo
  end

  def update
    find_todo(@todo)
    @todo.update(todo_params)
    @todo.save
    # render :json => @todo
  end

  def destroy
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :address, :done, :description, :parent_id, :duedate, tasks_attributes: [:title, :parent_id, :todo_id, :id])
  end

  def find_todo(todo)
    @todo = Todo.find_by(id: params[:id])
  end

  def all_todos(parent)
    Todo.left_outer_joins(:parent).where('parent_id = ?', @parent.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def contact
  end

  def welcome
  end

  def terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/admin/edit.html.erb
<div class="panel panel-default">

  <div class="panel-heading">

    <h3 class="panel-title">edit <%= current_parent.name.downcase %></h3>
  </div>

  <div class="panel-body">

    <%= form_for(current_parent, url: admin_path(current_parent), controller: 'admin', action: 'patch') do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <br>
      <%= f.label :admin %>
      <br>
      <%= f.label 'yes' %><%= f.radio_button :admin, 'true' %>
      <%= f.label 'no' %><%= f.radio_button :admin, 'false' %>
      <br>
      <%= f.submit 'submit', :class => 'btn btn-primary' %>
    <% end %>
    <br>
    <%= link_to("delete user", admin_path, method: :delete, class: 'btn btn-danger') %>
    <br><br>
    <%= link_to 'return to all users', admin_index_path %>
    <br>
  </div>

app/views/admin/index.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">welcome to admin, <%= current_user.name.split(' ').first.downcase %></h3>
  </div>

  <div class="panel-body">

    <h4>users:</h4>

    <% @parents.order('id asc').each do |parent| %>
      <%= parent.id %>. <%= link_to parent.name, admin_path(parent) %>
      <br>
    <% end %>

  </div>

app/views/admin/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">viewing <%= current_parent.name.downcase %></h3>
  </div>

  <div class="panel-body">

    <h4><%= current_parent.name.split(' ').first.downcase %>'s info:</h4>

    <% if current_parent.image == nil || current_parent.image.empty? %>
      no image provided
    <% else %>
      <%= image_tag(current_parent.image, :width => 80) %>
    <% end %>

    <br>

    email: <%= current_parent.email %>
    <br>
    account created on: <%= current_parent.created_at.strftime('%B %d, %Y').downcase %>
    <br>
    id number: <%= current_parent.id %>
    <br>
    admin: <%= current_parent.admin %>

    <br><br>

    todos:
    <br>
    <% if current_parent.todos.empty? || current_parent.todos.nil? %>
      no todos currently
    <% else %>
      <% current_parent.todos.each do |todo| %>
        <%= todo.title %>
      <% end %>
    <% end %>

    <br><br>
    
    <%= link_to 'edit this user', edit_admin_path(current_parent) %>
    <br>
    <%= link_to 'return to all users', admin_index_path %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="parents getting stuff done with parental.">
    <meta name="author" content="ben greenberg">
    <%= favicon_link_tag 'favicon.ico' %>
    <meta property="og:image" content='<%= image_url 'parental_todo.jpg' %>'/>
    <title>parental -- get stuff done.</title>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.10/handlebars.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>

  </head>

    <body>

      <div class="site-wrapper">

        <div class="site-wrapper-inner">

          <div class="cover-container">

            <div class="masthead clearfix">
              <div class="inner">
                <h3 class="masthead-brand">parental - <em>get stuff done.</em></h3>
                <nav>
                  <ul class="nav masthead-nav">
                    <% if current_user %>
                      <li class="active"><%= link_to 'Home', parent_path(current_user) %></li>
                    <% else %>
                      <li class="active"><%= link_to 'Home', root_path %></li>
                    <% end %>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                  </ul>
                </nav>
              </div>
            </div>

            <div class="inner cover">
              <%= yield %>

            </div>

            <div class="mastfoot">
              <div class="inner">

                  <p>
                    <% if current_user %>
                      <%= link_to 'logout', '/logout' %> | <%= link_to 'privacy policy', '/terms' %></p>
                    <% else %>
                      <%= link_to 'login', '/login' %> | <%= link_to 'signup', '/registrations/new' %> | <%= link_to 'contact', '/contact' %> | <%= link_to 'privacy policy', '/terms' %></p>
                    <% end %>
                  <p>&copy;2017 <a href="http://www.bengreenberg.org">Ben Greenberg</a>&nbsp;
                    <%= link_to admin_index_path do %>
                      <%= image_tag("key_icon.png", :width => 20) %>
                    <% end %>
                  </p>

              </div>
            </div>

          </div>

        </div>

      </div>

      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    </body>
  </html>

</html>

app/views/parents/_todo.html.erb
<div class="todo-address">
<% if @current_todo != nil %>
    <%= form_for([current_user, @current_todo], :html => {:id => 'address-form'}) do |f| %>
      <%= f.label :address, "add an address:" %><br>
      <%= f.text_field :address, :placeholder => 'enter a street address', size: 22 %>
      <br>
      <%= f.submit 'submit', :class => 'btn btn-primary', :id => 'submit-address' %>
    <% end %>
  <% end %>
</div>

<div class="todo-description">
<% if @current_todo != nil %>
  <%= form_for([current_user, @current_todo], :html => {:id => 'description-form'}) do |f| %>
    <%= f.label :description, "add some info" %>
    <br>
    <%= f.text_area :description %>
    <br>
    <%= f.submit 'add description', :class => 'btn btn-primary', :id => 'submit-description' %>
  <% end %>
<% end %>
<br>
</div>


<div class="todo-duedate">
<% if @current_todo != nil %>
  <%= form_for([current_user, @current_todo], :html => {:id => 'duedate-form'}) do |f| %>
    <%= f.label :duedate, "needs to get done by?" %>
    <br>
    <%= f.date_field :duedate, :value => @current_todo.duedate %>
    <br>
    <%= f.submit 'add due date', :class => 'btn btn-primary', :id => 'submit-duedate' %>
  <% end %>
<% end %>
<br>
</div>


<div class="todo-addtask">

</div>


<div class="todo-taskdone">
</div>


<div class="todo-done">
<% if @current_todo != nil %>
  <%= form_for([current_user, @current_todo], :html => {:id => 'tododone-form'}) do |f| %>
    <%= f.label "yes?" %>
    <%= f.radio_button :done, "true" %>
    <%= f.label "no?" %>
    <%= f.radio_button :done, "false" %>
    <br>
    <%= f.submit 'mark done', :class => 'btn btn-primary', :id => 'submit-tododone' %>
  <% end %>
<% end %>
<br>
<%= link_to 'return to your todos', parent_path(@parent), :style => 'color: black'  %>
</div>

</div>

app/views/parents/index.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">welcome.</h3>
  </div>

  <div class="panel-body">

    <div id="welcome-msg">
      <img src="<%= current_user.image %>">&nbsp;<em>hi, <%= current_user.name.split(' ').first.downcase %>. what would you like to do?</em>
    </div>

    <br><br>

    <div class="todo-content">

    
    </div>

      <br>

    </div>
  </div>

app/views/parents/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">welcome.</h3>
  </div>

  <div class="panel-body">

    <div id="welcome-msg">
      <img src="<%= current_user.image %>">&nbsp;<em>hi, <%= current_user.name.split(' ').first.downcase %>. what would you like to do?</em>
    </div>

    <br><br>

    <div class="todo-content">

    <h4>add something to do</h4>
    <div id="main-todo-form">
      <%= form_for([@parent, @todo]) do |f| %>
       <%= f.text_field :title, :placeholder => 'what needs to get done?', size: 22 %>
        <br>
        <%= f.text_field :address, :placeholder => 'enter a street address', size: 22 %>
        <br>
        <%= f.fields_for :tasks, @todo.tasks.new do |t| %>
          <%= t.text_field :title, :placeholder => 'add a todo', size: 22 %>
          <%= t.hidden_field :parent_id, :value => @parent.id %>
          <%= t.hidden_field :todo_id, :value => @todo.id %>
        <% end %>
        <br>
        <%= f.fields_for :tasks, @todo.tasks.new do |t| %>
          <%= t.text_field :title, :placeholder => 'add a todo', size: 22 %>
          <%= t.hidden_field :parent_id, :value => @parent.id %>
          <%= t.hidden_field :todo_id, :value => @todo.id %>
        <% end %>
        <br>
        <%= f.submit "add todo", :id => 'todo-submit', :class => 'btn btn-primary' %>
      <% end %>
    </div>

    <br><br>

    <h4>your todo list</h4>
    <div class="todo-list">
    <% @todos.each do |todo| %>
      <% if todo.done == false %>
        <strong>
           <a href="/parents/<%= @parent.id %>/todos/<%= todo.id %>" 
            class="load_todo" 
            data-todoid="<%= todo.id %>" 
            data-parentid="<%= current_user.id %>" 
            data-title="<%= todo.title %>" 
            data-tasks="<%= todo.tasks.each do |task| end %>" 
            data-description="<%= todo.description %>"
            data-done="<%= todo.done %>"
            data-duedate="<%= todo.duedate %>"
            data-address="<%= todo.address %>"><%= todo.title %>
          </a>
        </strong>
      <% end %>
      <br>
    <% end%>
    </div>
    
    </div>
  </div>

<%= render "todo" if @tasks != nil && @current_todo != nil %>

app/views/todos/index.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">welcome.</h3>
  </div>

  <div class="panel-body">

    <img src="<%= current_user.image %>">&nbsp;<em>hi, <%= current_user.name.split(' ').first.downcase %>. what would you like to do?</em>

    <br><br>

    <h4>add something to do</h4>
    <%= form_for([@parent, @todo]) do |f| %>
      <%= f.text_field :title, :placeholder => 'what needs to get done?', size: 22 %>
      <br>
      <%= f.text_field :address, :placeholder => 'enter a street address', size: 22 %>
      <br>
      <%= f.fields_for :tasks do |t| %>
        <%= t.hidden_field :parent_id, :value => current_user.id %>
      <% end %>
      <br>
      <%= f.submit "add todo", :class => 'btn btn-primary' %>
    <% end %>

    <br><br>

    <h4>your todo list</h4>
      <% @todos.each do |todo| %>
        <% if todo.done == false %>
          <strong><%= link_to todo.title, todo_path(todo) %></strong>
          <br>
        <% end %>
      <% end %>

      <br>

      <p><%= link_to 'logout', logout_path %></p>
  </div>

</div>

app/views/todos/show.html.erb
<div class="panel panel-default">

<div class="panel-heading">
</div>

<div class="todo-address">
<%= form_for([current_user, @todo]) do |f| %>
  <%= f.label :address, "add an address:" %><br>
  <%= f.text_field :address, :placeholder => 'enter a street address', size: 22 %>
  <br>
  <%= f.submit 'submit', :class => 'btn btn-primary' %>
<% end %>
</div>

<div class="todo-description">
<%= form_for([current_user, @todo]) do |f| %>
  <%= f.label :description, "add some info" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <%= f.submit 'add description', :class => 'btn btn-primary' %>
<% end %>
</div>

<div class="todo-duedate">
<%= form_for([current_user, @todo]) do |f| %>
  <%= f.label :duedate, "needs to get done by?" %>
  <br>
  <%= f.date_field :duedate, :value => @todo.duedate %>
  <br>
  <%= f.submit 'add due date', :class => 'btn btn-primary' %>
<% end %>
</div>

<div class="todo-addtask">

</div>

<div class="todo-taskdone">
<% @tasks.each do |task| %>
  <% if task.done == false %>
    <%= form_for(task, :url => parent_todo_task_path(@todo.id, task.id)) do |f| %>
      <%= f.label 'y' %><%= f.radio_button :done, "true" %>
      <%= f.label 'n' %><%= f.radio_button :done, "false" %>
      <%= f.hidden_field :task_id, :value => task.id %>
      <%= f.submit 'mark done', :class => 'btn btn-primary btn-xs' %>
    <% end %>
  <% end %>
<% end %>
</div>

<div class="todo-done">
<%= form_for([current_user, @todo]) do |f| %>
  <%= f.label "yes?" %>
  <%= f.radio_button :done, "true" %>
  <%= f.label "no?" %>
  <%= f.radio_button :done, "false" %>
  <br>
  <%= f.submit 'mark done', :class => 'btn btn-primary' %>
<% end %>
</div>

<div class="panel panel-default">
    <div class="panel-body">
      <%= link_to 'return to your todos', parent_path %>
      <br>
      <%= link_to 'logout', logout_path %>
  </div>

app/views/welcome/about.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">about</h3>
  </div>

  <div class="panel-body">

    <h4>parental is about getting stuff done</h4>

    <br>

    <strong>you have lots of things to remember to do</strong>

    <br><br>

    <em>
      did you get the groceries? did you pick up the new baseball helmet? did you sign up for the after school activity? what about dinner tonight, school lunch tomorrow and the birthday cake for the weekend?
    </em>

    <br><br>

    <strong>parental is a free resource to help you organize your things to do</strong>

    <br><br>

    &rarr; create an account and start adding your todos to your profile

    <br>

    &rarr; each todo is embedded with google maps so you can easily get directions

    <br>

    &rarr; add tasks for each todo

    <br>

    &rarr; go ahead and mark each task done when you finish it

    <br>

    &rarr; and feel the <em>great relief</em> of marking an entire todo finally done

    <br><br>

    get started today easily by <%= link_to 'signing up', new_registration_path %> with your facebook account.

  </div>

app/views/welcome/contact.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">contact</h3>
  </div>

  <div class="panel-body">

    <%= link_to 'https://www.facebook.com/rabbigreenberg' do %>
      <%= image_tag("facebook_icon.png", :width => 118) %>
    <% end %>

    <%= link_to 'https://twitter.com/RabbiGreenberg' do %>
      <%= image_tag("twitter_icon.png", :width => 118) %>
    <% end %>

    <%= link_to 'https://www.linkedin.com/in/rabbigreenberg/' do %>
      <%= image_tag("linkedin_icon.png", :width => 118) %>
    <% end %>

    <%= link_to 'https://github.com/benhayehudi' do %>
      <%= image_tag("github_icon.png", :width => 128) %>
    <% end %>

  </div>

app/views/welcome/terms.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">terms of service and privacy policy.</h3>
  </div>

  <div class="panel-body">

  1. Terms
  <br>
  By accessing the website at http://parental.life, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.
  <br><br>
  2. Use License
  <br>
  Permission is granted to temporarily download one copy of the materials (information or software) on parental -- get stuff done's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
  modify or copy the materials;
  use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
  attempt to decompile or reverse engineer any software contained on parental -- get stuff done's website;
  remove any copyright or other proprietary notations from the materials; or
  transfer the materials to another person or "mirror" the materials on any other server.
  This license shall automatically terminate if you violate any of these restrictions and may be terminated by parental -- get stuff done at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
  <br><br>
  3. Disclaimer
  <br>
  The materials on parental -- get stuff done's website are provided on an 'as is' basis. parental -- get stuff done makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
  Further, parental -- get stuff done does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.
  <br><br>
  4. Limitations
  <br>
  In no event shall parental -- get stuff done or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on parental -- get stuff done's website, even if parental -- get stuff done or a parental -- get stuff done authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
  <br><br>
  5. Accuracy of materials
  <br>
  The materials appearing on parental -- get stuff done's website could include technical, typographical, or photographic errors. parental -- get stuff done does not warrant that any of the materials on its website are accurate, complete or current. parental -- get stuff done may make changes to the materials contained on its website at any time without notice. However parental -- get stuff done does not make any commitment to update the materials.
  <br><br>
  6. Links
  <br>
  parental -- get stuff done has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by parental -- get stuff done of the site. Use of any such linked website is at the user's own risk.
  <br><br>
  7. Modifications
  <br>
  parental -- get stuff done may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.
  <br><br>
  8. Governing Law
  <br>
  These terms and conditions are governed by and construed in accordance with the laws of New York and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
  <br><br>
  Privacy Policy
  <br>
  Your privacy is important to us.
  <br>
  It is parental -- get stuff done's policy to respect your privacy regarding any information we may collect while operating our website. Accordingly, we have developed this privacy policy in order for you to understand how we collect, use, communicate, disclose and otherwise make use of personal information. We have outlined our privacy policy below.
  <br>
  We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
  <br>
  We will collect and use personal information solely for fulfilling those purposes specified by us and for other ancillary purposes, unless we obtain the consent of the individual concerned or as required by law.
  <br>
  Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
  <br>
  We will protect personal information by using reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
  <br>
  We will make readily available to customers information about our policies and practices relating to the management of personal information.
  <br>
  We will only retain personal information for as long as necessary for the fulfilment of those purposes.
  <br>
  We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. parental -- get stuff done may change this privacy policy from time to time at parental -- get stuff done's sole discretion.
</div>